# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_auto_20161025_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='test_field',
            field=models.BooleanField(default=True),
        ),
    ]
